### ISSUE TITLE
nim.h

### ISSUE THREAD

**Issue by Ali200303** [ETS-Fall-2023-GR03-INF155/.github#1]
/*******************************************************************************/
/*  NIM.H                                                                      */
/*  Ce module contient les fonctions necéssaires à l'implémantation du jeu NIM */
/*******************************************************************************/
#ifndef MANIP_PLATEAU_H_
#define MANIP_PLATEAU_H_

#include "codage_numerique.h"
//#include "m_distributions.h"

#define PLATEAU_MAX_COLONNES 20		//Nombre maximal de colonnes sur le plateau
#define PLATEAU_MAX_PIECES 35		//Nombre maximal de pièces par colonne
#define TRUE   1
#define FALSE  0

/*******************************************************************************/
/*                   DÉCLARATION DES FONCTIONS PUBLIQUES                       */
/*******************************************************************************/

void plateau_init(int plateau[], int nb_colonnes);

void plateau_afficher(const int plateau[], int nb_colonnes, int col_select);

int nim_jouer_tour(int plateau[], int nb_colonnes, int colonne,
    int nb_pieces);

void plateau_supprimer_colonne(int plateau[], int nb_colonnes,
    int col_a_supprimer);

int plateau_defragmenter(int plateau[], int nb_colonnes);

void nim_choix_ia_aleatoire(const int plateau[], int nb_colonnes,
    int* choix_colonne, int* choix_nb_pieces);

void nim_choix_ia(const int plateau[], int nb_colonnes, int niveau,
    int* choix_colonne, int* choix_nb_pieces);

static int choisir_colonne(int plateau[], int nb_colonnes);

void tour_humain(int plateau[], int nb_colonnes);

void tour_ia(int plateau[], int nb_colonnes, double difficulte);

void demarrer_jeu(int niveau);

#endif

**Comment by Vianpyro** [comment]
Veuillez créer un dépôt pour votre équipe!
