### ISSUE TITLE
Nim_IO.c

### ISSUE THREAD

**Issue by Ali200303** [ETS-Fall-2023-GR03-INF155/.github#2]
#include "nim_io.h"

void plateau_afficher(const int plateau[], int nb_colonnes, int col_select)
{

	for (int i = 0; i < nb_colonnes; i++) {
		if (i == col_select) 
		{
			printf(" [%d] ", plateau[i]);
		}
		else {
			printf(" %d ", plateau[i]);
		}
	}
	printf("\n");
}

**Comment by Vianpyro** [comment]
Veuillez créer un dépôt pour votre équipe!
